version: '3'
services:
  #Buscador de Twitters
  alfred:
    build: 
      dockerfile: ./Alfred/dockerfile
      context: .
    image: 'gumberss/twitter-finder-alfred'
    container_name: Alfred
    ports:
      - 3001:3000
    networks:
      - twitter-finder-network
    depends_on:
      - heimdall
  
  #Armazenador dos twitters
  heimdall:
    image: mongo
    networks: 
      - twitter-finder-network

networks:
  twitter-finder-network:
    driver: bridge